# Generated by Django 2.1.5 on 2020-04-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0010_auto_20200420_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.genre'),
        ),
    ]
