# Generated by Django 2.1.5 on 2020-04-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_auto_20200421_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.genre'),
        ),
    ]
